import { CurriculumItem } from './types';

const originalCurriculum: Omit<CurriculumItem, 'id'>[] = [
  { graduation: 'Fundamental', study: 'Expressão do Crescimento Vertical (Tyokusseitai) (直生体)', varietySuggestion: 'Moribana' },
  { graduation: 'Fundamental', study: 'Expressão do Crescimento Oblíquo (Shasseitai) (斜生体)', varietySuggestion: 'Moribana' },
  { graduation: 'Fundamental', study: 'Expressão do Crescimento Horizontal (Ousseitai) (横生体)', varietySuggestion: 'Moribana' },
  { graduation: 'Fundamental', study: 'Expressão do Crescimento Pendente (Suisseitai) (垂生体)', varietySuggestion: 'Moribana' },
  { graduation: 'Fundamental', study: 'Agrupamento (Shugo) (集合)', varietySuggestion: 'Moribana' },
  { graduation: 'Fundamental', study: 'Expressão de Três Faces (Sanpo Shomen) (三方正面)', varietySuggestion: 'Moribana' },
  { graduation: 'Fundamental', study: 'Expressão de Quatro Faces (Shiho Shomen) (四方正面)', varietySuggestion: 'Moribana' },
  { graduation: 'Fundamental', study: 'Centro de Mesa (Takujyoka) (卓上花)', varietySuggestion: 'Moribana' },
  { graduation: 'Fundamental', study: 'Expressão de Simplificação (Shoryaku) (省略)', varietySuggestion: 'Moribana' },
  { graduation: 'Fundamental', study: 'Expressão de Ângulo Forma completa/estrutural (Taikaku) (体格)', varietySuggestion: 'Moribana' },
  { graduation: 'Intermediário', study: 'Técnicas de fixação', varietySuggestion: 'Nageire' },
  { graduation: 'Intermediário', study: 'Coesão de Duas Linhas (Nikaku Kossei) (二格構成)', varietySuggestion: 'Nageire' },
  { graduation: 'Intermediário', study: 'Expressão de Simplificação (Shoryaku) (省略)', varietySuggestion: 'Nageire' },
  { graduation: 'Intermediário', study: 'Expressão de Ângulo (Taikaku)(体格)', varietySuggestion: 'Nageire' },
  { graduation: 'Intermediário', study: 'Linha Reta (Tyoku Sen) (直線) Radiante', varietySuggestion: 'Moribana' },
  { graduation: 'Intermediário', study: 'Linha Reta (Tyoku Sen) (直線) Oblíqua', varietySuggestion: 'Moribana' },
  { graduation: 'Intermediário', study: 'Linha Reta (Tyoku Sen) (直線) Paralela', varietySuggestion: 'Moribana' },
  { graduation: 'Intermediário', study: 'Linha Curva (Kyoku Sen) (曲線) Curva semicircular', varietySuggestion: 'Moribana' },
  { graduation: 'Intermediário', study: 'Linha Curva (Kyoku Sen) (曲線) Dinâmica', varietySuggestion: 'Moribana' },
  { graduation: 'Intermediário', study: 'Linha Curva (Kyoku Sen) (曲線) Sinuosas', varietySuggestion: 'Moribana' },
  { graduation: 'Intermediário', study: 'Linha Reta (Tyoku Sen) (直線) Radiante', varietySuggestion: 'Nageire' },
  { graduation: 'Intermediário', study: 'Linha Reta (Tyoku Sen) (直線) Oblíqua', varietySuggestion: 'Nageire' },
  { graduation: 'Intermediário', study: 'Linha Curva (Kyoku Sen) (曲線) Curva semicircular', varietySuggestion: 'Nageire' },
  { graduation: 'Intermediário', study: 'Linha Curva (Kyoku Sen) (曲線) Dinâmica', varietySuggestion: 'Nageire' },
  { graduation: 'Intermediário', study: 'Linha Curva (Kyoku Sen) (曲線) Sinuosas', varietySuggestion: 'Nageire' },
  { graduation: 'Avançado', study: 'Estudo de Linha (Sen) (線)', varietySuggestion: 'Moribana' },
  { graduation: 'Avançado', study: 'Estudo de Face (Men) (面)', varietySuggestion: 'Moribana' },
  { graduation: 'Avançado', study: 'Estudo de Volume (Massu) (塊)', varietySuggestion: 'Moribana' },
  { graduation: 'Avançado', study: 'Estudo de Face e Volume (Men Massu) (面塊)', varietySuggestion: 'Moribana' },
  { graduation: 'Avançado', study: 'Estudo de Linha (Sen) (線)', varietySuggestion: 'Nageire' },
  { graduation: 'Avançado', study: 'Estudo de Face (Men) (面)', varietySuggestion: 'Nageire' },
  { graduation: 'Avançado', study: 'Estudo de Volume (Massu) (塊)', varietySuggestion: 'Nageire' },
  { graduation: 'Avançado', study: 'Estudo de Face e Volume (Men Massu) (面塊)', varietySuggestion: 'Nageire' },
  { graduation: 'Avançado', study: 'Estudo de Linha e Face (Sen Men)(線面)', varietySuggestion: 'Moribana' },
  { graduation: 'Avançado', study: 'Estudo de Linha e Volume (Sen Massu) (線塊)', varietySuggestion: 'Moribana' },
  { graduation: 'Avançado', study: 'Estudo de Face e Volume (Men Massu) (面塊)', varietySuggestion: 'Moribana' },
  { graduation: 'Avançado', study: 'Estudo de Linha, Face e Volume (Sen Men Massu) (線面塊)', varietySuggestion: 'Moribana' },
  { graduation: 'Avançado', study: 'Segmentação (Bunkatsu) (分割)', varietySuggestion: 'Moribana' },
  { graduation: 'Avançado', study: 'Conjunto (Heigo) (併合) Combinação/União', varietySuggestion: 'Moribana' },
  { graduation: 'Avançado', study: 'Cruzamento (kossa) (交差)', varietySuggestion: 'Moribana' },
  { graduation: 'Avançado', study: 'Estudo de Linha e Volume (Sen Massu) (線塊)', varietySuggestion: 'Nageire' },
  { graduation: 'Avançado', study: 'Estudo de Linha, Face e Volume (Sen Men Massu) (線面塊)', varietySuggestion: 'Nageire' },
  { graduation: 'Avançado', study: 'Conjunto (Heigo) (併合) Combinação/União', varietySuggestion: 'Nageire' },
  { graduation: 'Avançado', study: 'Cruzamento (kossa) (交差)', varietySuggestion: 'Nageire' },
  { graduation: 'Avançado', study: 'Linha (Sen) (線) com Flor /e ou Folha', varietySuggestion: 'Moribana' },
  { graduation: 'Avançado', study: 'Face (Men) (面) Fina, Larga, Grande, Pequena..', varietySuggestion: 'Moribana' },
  { graduation: 'Avançado', study: 'Volume (Massu) (塊) com Galho e Fruto', varietySuggestion: 'Moribana' },
  { graduation: 'Avançado', study: 'Linha, Face e Volume (Sen Men Massu) (線面塊)', varietySuggestion: 'Moribana' },
  { graduation: 'Avançado', study: 'Linha (Sen) (線) com Flor /e ou Folha', varietySuggestion: 'Nageire' },
  { graduation: 'Avançado', study: 'Face (Men) (面) Fina, Larga, Grande, Pequena..', varietySuggestion: 'Nageire' },
  { graduation: 'Avançado', study: 'Volume (Massu) (塊) com Galho e Fruto', varietySuggestion: 'Nageire' },
  { graduation: 'Avançado', study: 'Linha, Face e Volume (Sen Men Massu) (線面塊)', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Estudo do Vaso', varietySuggestion: 'Moribana' },
  { graduation: 'Senshukai', study: 'Estudo de Cor', varietySuggestion: 'Moribana' },
  { graduation: 'Senshukai', study: 'Translúcido', varietySuggestion: 'Moribana' },
  { graduation: 'Senshukai', study: 'Detalhe do Vaso', varietySuggestion: 'Moribana' },
  { graduation: 'Senshukai', study: 'Estudo do Vaso', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Estudo de Cor', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Translúcido', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Detalhe do Vaso', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Expressão de Três Faces (Sanpo - Shomen) (三方正面)', varietySuggestion: 'Moribana' },
  { graduation: 'Senshukai', study: 'Expressão de Quatro Faces (Shiho-Shomen) (四方正面)', varietySuggestion: 'Moribana' },
  { graduation: 'Senshukai', study: 'Expressão de Centro de Mesa (Takujyoka)(卓上花)', varietySuggestion: 'Moribana' },
  { graduation: 'Senshukai', study: 'Expressão de Três Faces (Sanpo - Shomen) (三方正面)', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Expressão de Quatro Faces (Shiho-Shomen) (四方正面)', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Expressão de Centro de Mesa (Takujyoka)(卓上花)', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Vivificação na Parede (Kakebana) (掛花)', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Vivificação Pendente (Tsuribana) (釣花)', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Mukaebana (迎花) - "Flor de boas-vindas" recepção', varietySuggestion: 'Moribana' },
  { graduation: 'Senshukai', study: 'Mukaebana (迎花) - "Flor de boas-vindas" recepção', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Taisaku (対作) - Arranjo em par/composição dupla', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Estudo de Assimetria', varietySuggestion: 'Moribana' },
  { graduation: 'Senshukai', study: 'Estudo de Harmonia e Contraste', varietySuggestion: 'Moribana' },
  { graduation: 'Senshukai', study: 'Estudo de Cor', varietySuggestion: 'Moribana' },
  { graduation: 'Senshukai', study: 'Estudo do Vaso (Proporção Desproporção)', varietySuggestion: 'Moribana' },
  { graduation: 'Senshukai', study: 'Estudo de Assimetria', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Estudo de Harmonia e Contraste', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Estudo de Cor', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Estudo do Vaso (Proporção Desproporção)', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Expressão de Modernidade (Guendaifu) (現代風) Estilo contemporâneo', varietySuggestion: 'Moribana' },
  { graduation: 'Senshukai', study: 'Expressão de Suavidade (Fuga) (風雅) Elegancia', varietySuggestion: 'Moribana' },
  { graduation: 'Senshukai', study: 'Expressão de Maturidade (Fukaku) (深格) Forma profunda/avançada', varietySuggestion: 'Moribana' },
  { graduation: 'Senshukai', study: 'Expressão de Modernidade (Guendaifu) (現代風) Estilo contemporâneo', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Expressão de Suavidade (Fuga) (風雅) Elegancia', varietySuggestion: 'Nageire' },
  { graduation: 'Senshukai', study: 'Expressão de Maturidade (Fukaku) (深格) Forma profunda/avançada', varietySuggestion: 'Nageire' },
];

export const IKEBANA_CURRICULUM: CurriculumItem[] = originalCurriculum.map((item, index) => ({
  ...item,
  id: index + 1,
}));


export const GRADUATIONS = ['Fundamental', 'Intermediário', 'Avançado', 'Senshukai'];
